### ISSUE TITLE
Wybranie przystanku - tylko autobusy

### ISSUE THREAD

**Issue by suchoj** [PiotrMachowski/Home-Assistant-custom-components-Rozkladzik#1]
Cześć,
Dodałem Rozkładzik do swojego HA, ale nie mogę wybrać odpowiedniego przystanku (Bardzka, Wrocław) - jak się kliknie na ikonkę przystanku i wyskakuje menu (Rozkład przystanku, Rozkład grupy...) to po wybraniu pierwszej opcji są tylko autobusy, a po wybraniu grupy jest razem z tramwajami, ale link pokazuje b=, a nie ma t= (timetable.txt?c=bsa&b=126&sid=45415&day=3&time=790).

Da się to jakoś zrobić, żeby było i to i to?

PS. Jeżeli chcesz, to mogę pisać po angielsku. Nie wiem, jakie są tu standardy. Dopiero zaczynam z GitHubem :)

PS. Dzięki za Twoją pracę - super robota!

**Comment by PiotrMachowski** [comment]
Cześć,

Sprawa jest trochę bardziej złożona. Tramwaje powinny być wyświetlane po wybraniu rozkładu przystanku, także jest to problem z danymi na stronie _Rozkładzik_, na co nic nie jestem w stanie poradzić. Po wybraniu grupy przystanków wyświetlane są połączenia w obie strony, a że jeszcze nie doszedłem jak pobrać kierunek, to po wyświetleniu byłoby ciężko określić który odjazd nas interesuje.
Planuję dodać wsparcie dla grup przystanków, może po drodze uda mi się bardziej zgłębić działanie serwisu, żeby odnaleźć interesujące mnie dane.

Wydaje mi się, że sprawy są głównie załatwiane po angielsku, ale ta integracja jest dedykowana dla polskiego serwisu, więc chyba można pisać po polsku.

**Comment by suchoj** [comment]
Zmieniłem w linii 82 url_template (tam gdzie było tsa i t na bsa i b) i udało się :)
ORYG:
```
url_template = 'https://www.rozkladzik.pl/{}/timetable.txt?c=tsa&t={}&day={}&time={}'
```
ZMIENIONE:
```
url_template = 'https://www.rozkladzik.pl/{}/timetable.txt?c=bsa&b={}&day={}&time={}'
```
> Po wybraniu grupy przystanków wyświetlane są połączenia w obie strony

Co do kierunku, to nie miałem z tym problemu w przypadku mojego przystanku. Po przybliżeniu mapy przystanek w każdym kierunku jest odzielnie, więc wybieram ten mnie interesujący, ale:

- kliknięcie na przystanku 'Rozkład przystanku' pokazuje tylko autobusy w danym kierunku - żeby pobrać ten rozkład link z linijki 82 musi być jak oryginalny (tsa i t)

- kliknięcie 'Rozkład grupy' pokazuje autobusy i tramwaje w dwóch kierunkach - żeby pobrać ten rozkład link z linijki 82 musi być jak zmieniony (bsa i b)

I tu dzieje się magia - niby pobieram rozkłady, które wyświetlają mi się po kliknięciu 'Rozkład grupy', czyli w różnych kierunkach (przynajmniej na stronie rozkładzik tak się pokazuje tabela), ale tak na prawdę w HA mam tylko w prawidłowym kierunku.

Sprawdzę to później dla innych przystanków i dam znać. Możesz mi też napisać jakiś przykład przystanku, gdzie do HA pobrane zostały dwa kierunki - może coś mi się uda zauważyć.

**Comment by suchoj** [comment]
Zweryfikowałem na kilku przystankach i rzeczywiście dla przycisku "Rozkład grupy przystanków" mimo, że na stronie wyświetla dwa kierunki, to do HA pobiera tylko odjazdy w jednym.

**Comment by PiotrMachowski** [comment]
W sumie to dziwne, jak będę miał czas, to rzucę okiem. Teraz mam dużo innych spraw rozgrzebanych, także rozkładzik spadł na drugi plan

**Comment by PiotrMachowski** [comment]
W releasie v1.1.0 dodałem wsparcie dla grup przystanków, rozwiązując przy okazji problem z wyświetlaniem odjazdów w jednym kierunku.
