### ISSUE TITLE
Informacje / Dokumentacja nieoficjalnego API

### ISSUE THREAD

**Issue by justkowal** [PiotrMachowski/Home-Assistant-custom-components-Rozkladzik#10]
Czy istnieje jakakolwiek dokumentacja nieoficjalnego API?
Od paru dni szukam jakiś informacji, to jedyne co odnalazłem. Staram się stworzyć integrację dla Asystenta Google, to repozytorium to kawał dobrej roboty pod wzgledem inżynierii wstecznej lecz potrzebne mi są niektóre funkcje które są zaimplementowane lecz nie są użyte np. przystanki w danej linii są w teorii dekodowane przez funkcję `get_city_data()` lecz same wartości w tej tabeli pozostają zagadką (próbowałem zestawiać ze sobą wartości z tabeli i ręcznie pobrane ID przystanków lecz od kilku dni nie mogę znaleźć niczego sensownego). Jeśli były jakieś plany by użyć tych funkcji lecz zostały one porzucone mimo tego że metoda dekodowania tych liczb istnieje to bardzo proszę o pokazanie jej.

Z góry dziękuję

**Comment by PiotrMachowski** [comment]
Niestety nic nie ma, musiałem samemu się bawić i sprawdzać. Rozkładzik sam w sobie też chyba nie do końca jest zadowolony z tej integracji, bo wprowadzili blokowanie adresów IP. Funkcja `get_city_data` jest użyta do nadania wartości `self._city_data`, która jest używana w funkcji `get_direction`. 

Struktura danych zwracanychw  get_city_data z tego, co pamiętam jest taka:

```
{
    "nazwa linii": 
        (
            "nazwa linii",
            [
                (
                    <id przystanku końcowego w danym kierunku>,
                    "nazwa przystanku końcowego w danym kierunku"
                    [ <lista id przystanków dla danego kierunku> ]
                ),
                ...
            ]
        ),
    ...
}
```

Przykład dla Wrocławia (wycinek) dla linii K (ma dwa kierunki; [Rozkład](https://www.wroclaw.pl/komunikacja/linia-k-wroclaw)) i N (ma dwa kierunki, [Rozkład](https://www.wroclaw.pl/komunikacja/linia-n-wroclaw)):

```
{
    "K": 
        (
            "K",
            [
                (
                    264, 
                    "Gaj - Pętla",
                    ["7196", "7197", "11805", "11806", "11807", "7200", "1603", "1619", "18513", "8342", "8343", "7205", "15", "69", "6189", "6190", "6191", "7210", "9508", "9928", "9545", "7214", "9048", "9049", "8484", "7218", "7219"]
                ),
                (
                    254,
                    "Kamieńskiego (Pętla)",
                    ["7168", "7169", "9052", "9053", "8577", "7173", "9929", "9930", "9931", "7177", "13339", "13340", "13341", "13342", "3351", "72", "233", "7182", "18889", "18890", "11825", "11826", "11985", "9649", "11808", "11809", "11810", "18891", "5655", "5657", "5658", "6753", "6759"]
                )
            ]
        ), 
    "N": 
        (
            "N", 
            [
                (
                    277, 
                    "Litewska", 
                    ["9511", "9512", "9523", "9524", "7250", "7251", "7252", "7253", "7614", "9879", "9880", "5440", "5441", "5442", "9883", "9884", "9885", "9886", "18904", "18905", "18541", "5577", "9847", "9848", "9849", "5437", "5438", "5439", "9230", "2222", "2234", "4877", "4878", "7258", "7259", "7260", "7261", "7262", "7263", "11317", "11318"]
                ),
                (
                    2077,
                    "Petrusewicza",
                    ["11319", "5516", "7268", "7269", "7270", "7271", "7272", "7273", "4814", "4874", "2235", "8483", "2618", "2656", "5640", "9232", "9233", "9234", "9236", "9237", "9240", "9861", "7277", "7278", "7279", "7280", "7281", "7282", "18537", "18538", "12010", "18906"]
                )
            ]
        )
}
```

**Comment by justkowal** [comment]
Dzięki za szybką odpowiedź, element który mnie ciekawi to id przystanków. Nie odpowiadają one id używanym w innych funkcjach (co z resztą widać bo w takiej Częstochowie w której testuje swoją aplikację nie ma przecież 3000 przystanków a sama tabela nazw zwrócona przez `get_city_data()` po drobnej edycji ma chyba ~500 elementów). Rozumiem że nie wiadomo jak zmodyfikować id pochodzące z tabeli zawartej w obiekcie kierunku tak by można było je użyć np. przy pobieraniu rozkładu?
```
254,
"Kamieńskiego (Pętla)",
Mowa o tej tabeli id przystanków -> ["7168", "7169", "9052", "9053", "8577", "7173", "9929", "9930", "9931", "7177", "13339", "13340", "13341", "13342", "3351", "72", "233", "7182", "18889", "18890", "11825", "11826", "11985", "9649", "11808", "11809", "11810", "18891", "5655", "5657", "5658", "6753", "6759"]
```

Poza tym to jakiś absurd że darmowe rozwiązanie wspierane przez wiele miast wiec de facto opłacane z pieniędzy podatników nie posiada swojego oficjalnego API. Jak sie wkurzę to napiszę do jakdojade.pl o dostęp i tyle. Powinni brać przykład z innych miast które opublikowały nawet dane na żywo w rządowym serwisie "Otwarte Dane"

**Comment by justkowal** [comment]
Wydawało mi się że są jakieś niewielkie szanse na przydzielenie dostępu dla ciekawych projektów za darmo. Po cichu liczę że będę miał farta i go otrzymam. Co do tych id, z pewnością nie są to te same co używane do pobierania rozkładów, będę jeszcze próbował walczyć z nimi...

Dzięki za pomoc i życzę miłego popołudnia
