### ISSUE TITLE
Reduce insensitivity of API calls

### ISSUE THREAD

**Issue by PiotrMachowski** [PiotrMachowski/Home-Assistant-custom-components-Rozkladzik#2]
Recently Rozkladzik introduced mechanizm that blocks IP addresses that generate too much traffic.

ERROR: Connection refused

**Comment by xury77** [comment]
Yes I can confirm. My home IP is banned to get in to  after 3 hours of start using this integration

**Comment by porebas** [comment]
My IP is also banned.
Is it possible to reduce traffic, to avoid IP blocks ?

**Comment by peetereczek** [comment]
I also got ban :/

**Comment by ciechompl** [comment]
same here.
Any chance to add some small option which would allow users to define how often sensor should get data from Rozkladzik ?

**Comment by ciechompl** [comment]
Just an idea for a quick and dirty bypass :) 
Would it work if we add small if (e.g.: `if now.minute = 15 or now.minute = 30 ...` ) just before line:
`response = requests.get(url_template.format(self._city, self._stop_id, now.weekday(), r_time))`
in  `def update(self)` ? 
I know that this is not as it should be but at least for now it could limit API call to 1 per 15 min or ?

**Comment by PiotrMachowski** [comment]
@ciechompl Limiting API calls to one per X minutes is easy, the problem is that Rozkładzik returns only 5 departures, so delays between updates should correspond to frequency of departures.

My idea is to wait with update of a sensor until the first departure, but I didn't have time to implement it

**Comment by ciechompl** [comment]
ok, but could you (at least for a time being as a dirty workaround :)) add this option with "one api call per X minutes" ? 
Everyone can play with it for a while and at least in my case one call per 5 min is completely enough as usually there is no more departures than one per 5 min :)

**Comment by ciechompl** [comment]
Piotr please also consider creating new integration/component :) ... have a look on this: https://przyjazdy.pl/api-doc 
Seems to be much more official, with full API and free in non commercial use. 
PS:
I could not find any other (than yours rozkladzik component) working solution for PL so the only hope is with you :)

**Comment by ciechompl** [comment]
I found quick solution/workaround ... 
In sensor definition you can add  ```scan_interval: 120```  (source: https://www.home-assistant.io/docs/configuration/platform_options/) 
In my case 120 s works perfectly and I'm not banned since yesterday (at least no yet :-)

**Comment by PiotrMachowski** [comment]
I have optimized a number of API calls in version v.1.1.1, please check if it works for you. Additionally I have added a possibility to filter departures

**Comment by ciechompl** [comment]
I'm getting this error in log:

```
2020-02-25 16:57:55 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.rozkladzik_lublin_307 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/rozkladzik/sensor.py", line 102, in update
    if self._should_update(now):
  File "/config/custom_components/rozkladzik/sensor.py", line 113, in _should_update
    return self._last_response is None or self._departures_ordered is None or len(self._departures_ordered) == 0 or self._departures_ordered[0][4] < now
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'
```

**Comment by PiotrMachowski** [comment]
My bad, fixed in v1.1.2

**Comment by ciechompl** [comment]
super thanks :) now seems to be working fine :)

**Comment by PiotrMachowski** [comment]
Great! Finally ;)
