### ISSUE TITLE
I need some help with initial configuration

### ISSUE THREAD

**Issue by raptyk** [PiotrMachowski/Home-Assistant-custom-components-Rozkladzik#4]
Czesc, zainstalowalem rozkladzik uzywajac HACS, nastepnie dodalem Lovelace Html Card oraz odpowiedni wpis w configuration.xaml. Zrestartowalem HA i... nic nie dziala. Dodam, ze to moje poczatki z HA i podejrzewam, ze pominalem jakis oczywisty krok albo nie wiem jak uzyc samej wtyczki. Konfigurujac karte nie moge dodac nowego elementu (nie pojawil sie zaden nowy typ), a przy probie wstawienia elementu jako custom pojawia sie blad. Szczegoly ponizej... Co moze byc nie tak ? 

![image](https://user-images.githubusercontent.com/5106486/77304829-4e9e3580-6cf5-11ea-87f3-3a3c72d5df2b.png)

![image](https://user-images.githubusercontent.com/5106486/77304814-49d98180-6cf5-11ea-8fda-4d77e5c18f31.png)

![image](https://user-images.githubusercontent.com/5106486/77304838-5231bc80-6cf5-11ea-9e21-3aac424176cf.png)

![image](https://user-images.githubusercontent.com/5106486/77304843-552cad00-6cf5-11ea-8832-66a94c3f20ba.png)

![image](https://user-images.githubusercontent.com/5106486/77304851-58279d80-6cf5-11ea-9ef1-f1ffb4b25685.png)

Z gory dziekuje za pomoc.
_PS. przydalby sie minitutorial z kilkoma screenami w readme.md_

**Comment by PiotrMachowski** [comment]
Cześć,

Konfiguracja sensora jest w porządku, ale podałeś kierunek, który jest niezgodny z tymi, które posiada Rozkładzik:
![image](https://user-images.githubusercontent.com/6118709/77423038-d146f380-6dce-11ea-81fe-bb5eff5d7324.png)

W konfiguracji karty musisz usunąć myślnik przed `type: ...` i podać poprawne ID encji.

**Comment by raptyk** [comment]
Super, dzieki - pomoglo

![image](https://user-images.githubusercontent.com/5106486/77425421-fa698300-6dd2-11ea-93e9-abe2a7450d48.png)
